create or replace function public.is_event_owner(p_event_id uuid) returns boolean language sql stable security definer set search_path='' as $$select exists(select 1 from public.events where id=p_event_id and created_by=auth.uid())$$;
create or replace function public.is_participant_in_event(p_event_id uuid) returns boolean language sql stable security definer set search_path='' as $$select exists(select 1 from public.teams where event_id=p_event_id and auth_user_id=auth.uid())$$;
create or replace function public.is_current_team(p_team_id uuid) returns boolean language sql stable security definer set search_path='' as $$select exists(select 1 from public.teams where id=p_team_id and auth_user_id=auth.uid())$$;
create or replace function public.coordinator_email_for_username(lookup_username text) returns text language sql stable security definer set search_path='' as $$select email::text from public.coordinators where username=lookup_username::citext$$;
revoke all on function public.coordinator_email_for_username(text) from public,anon,authenticated;grant execute on function public.coordinator_email_for_username(text) to service_role;

create or replace function public.create_event(p_event_name text,p_point_format public.point_format) returns public.events language plpgsql security definer set search_path='' as $$
declare e public.events; prefix text; code text;
begin if not exists(select 1 from public.coordinators where id=auth.uid()) then raise exception 'not_authorized';end if;prefix:=case when p_point_format='robo_race' then 'ROB' else 'DRN' end;
loop code:=prefix||to_char(now(),'YY')||upper(substr(encode(gen_random_bytes(3),'hex'),1,2));exit when not exists(select 1 from public.events where event_code=code);end loop;
insert into public.events(event_name,event_code,point_format,created_by) values(trim(p_event_name),code,p_point_format,auth.uid()) returning * into e;
insert into public.rounds(event_id,round_number,round_name) values(e.id,1,'Round 1');insert into public.round_teams(round_id,team_id) select r.id,t.id from public.rounds r join public.teams t on t.event_id=e.id where r.event_id=e.id and r.round_number=1;
if p_point_format='robo_race' then insert into public.scoring_rules(event_id,rule_key,rule_name,rule_type,seconds,operation) values(e.id,'line_touch','Line Touch','penalty',2,'subtract'),(e.id,'hand_touch','Hand Touch','penalty',3,'subtract'),(e.id,'bot_exit','Completely Bot Exit','penalty',5,'subtract'),(e.id,'obstacle_skip','Obstacle Skip','penalty',10,'subtract');else insert into public.scoring_rules(event_id,rule_key,rule_name,rule_type,seconds,operation) values(e.id,'ground_touch','Ground Touch','penalty',5,'subtract'),(e.id,'obstacle_hit','Obstacle Hit','penalty',4,'subtract'),(e.id,'obstacle_miss','Obstacle Miss','penalty',8,'subtract'),(e.id,'bonus','Bonus','bonus',1,'add'),(e.id,'perfect_landing','Perfect Landing','bonus',8,'add');end if;return e;end$$;

create or replace function public.coordinator_dashboard_stats() returns jsonb language sql stable security definer set search_path='' as $$select jsonb_build_object('total_events',(select count(*) from public.events where created_by=auth.uid()),'total_teams',(select count(*) from public.teams t join public.events e on e.id=t.event_id where e.created_by=auth.uid()),'active_rounds',(select count(*) from public.rounds r join public.events e on e.id=r.event_id where e.created_by=auth.uid() and r.status='active'),'completed_events',(select count(*) from public.events where created_by=auth.uid() and status='completed'))$$;

create or replace function public.save_score(p_round_id uuid,p_team_id uuid,p_total_time_seconds integer,p_details jsonb) returns public.scores language plpgsql security definer set search_path='' as $$
declare ev uuid;r public.rounds;s public.scores;d jsonb;rule public.scoring_rules;final integer:=p_total_time_seconds;
begin select * into r from public.rounds where id=p_round_id for update;if not found or not public.is_event_owner(r.event_id) then raise exception 'not_authorized';end if;if r.result_announced then raise exception 'round_locked';end if;select event_id into ev from public.teams where id=p_team_id;if ev is distinct from r.event_id or not exists(select 1 from public.round_teams where round_id=p_round_id and team_id=p_team_id and qualified) then raise exception 'invalid_team';end if;if p_total_time_seconds<0 then raise exception 'invalid_time';end if;
for d in select * from jsonb_array_elements(p_details) loop select * into rule from public.scoring_rules where id=(d->>'rule_id')::uuid and event_id=ev;if not found or (d->>'quantity')::integer<0 then raise exception 'invalid_rule';end if;final:=final+(case when rule.operation='add' then 1 else -1 end)*rule.seconds*(d->>'quantity')::integer;end loop;final:=greatest(0,final);
insert into public.scores(round_id,team_id,total_time_seconds,final_score_seconds) values(p_round_id,p_team_id,p_total_time_seconds,final) on conflict(round_id,team_id) do update set total_time_seconds=excluded.total_time_seconds,final_score_seconds=excluded.final_score_seconds,updated_at=now() returning * into s;delete from public.score_details where score_id=s.id;
for d in select * from jsonb_array_elements(p_details) loop select * into rule from public.scoring_rules where id=(d->>'rule_id')::uuid;insert into public.score_details(score_id,rule_id,quantity,calculated_seconds) values(s.id,rule.id,(d->>'quantity')::integer,rule.seconds*(d->>'quantity')::integer);end loop;
insert into public.audit_logs(user_id,event_id,action,entity_type,entity_id,new_value) values(auth.uid(),ev,'score_saved','score',s.id,to_jsonb(s));return s;end$$;

create or replace function public.set_round_status(p_round_id uuid,p_status public.round_status) returns public.rounds language plpgsql security definer set search_path='' as $$declare r public.rounds;begin select * into r from public.rounds where id=p_round_id for update;if not public.is_event_owner(r.event_id) then raise exception 'not_authorized';end if;if r.result_announced then raise exception 'round_locked';end if;update public.rounds set status=p_status,updated_at=now() where id=p_round_id returning * into r;return r;end$$;
create or replace function public.announce_round_result(p_round_id uuid) returns public.rounds language plpgsql security definer set search_path='' as $$declare r public.rounds;begin select * into r from public.rounds where id=p_round_id for update;if not public.is_event_owner(r.event_id) then raise exception 'not_authorized';end if;if r.result_announced then raise exception 'round_locked';end if;if not exists(select 1 from public.scores where round_id=p_round_id) then raise exception 'no_scores';end if;update public.rounds set status='locked',result_announced=true,announced_at=now(),updated_at=now() where id=p_round_id returning * into r;update public.events set status=case when r.round_number=1 then 'round_2_selection'::public.event_status else 'completed'::public.event_status end where id=r.event_id;insert into public.audit_logs(user_id,event_id,action,entity_type,entity_id,new_value) values(auth.uid(),r.event_id,'round_locked','round',r.id,to_jsonb(r));return r;end$$;

create or replace function public.generate_round_two(p_event_id uuid,p_method public.qualification_type,p_top_n integer default null,p_team_ids uuid[] default '{}') returns public.rounds language plpgsql security definer set search_path='' as $$declare r1 public.rounds;r2 public.rounds;begin if not public.is_event_owner(p_event_id) then raise exception 'not_authorized';end if;select * into r1 from public.rounds where event_id=p_event_id and round_number=1;if not r1.result_announced then raise exception 'round_one_not_locked';end if;insert into public.rounds(event_id,round_number,round_name) values(p_event_id,2,'Round 2') on conflict(event_id,round_number) do update set updated_at=now() returning * into r2;delete from public.round_teams where round_id=r2.id;if p_method='automatic_top_n' then insert into public.round_teams(round_id,team_id,qualification_type,qualified) select r2.id,s.team_id,p_method,true from public.scores s where s.round_id=r1.id order by s.final_score_seconds,s.team_id limit greatest(1,p_top_n);else insert into public.round_teams(round_id,team_id,qualification_type,qualified) select r2.id,t.id,p_method,true from public.teams t where t.event_id=p_event_id and t.id=any(p_team_ids);end if;update public.events set status='round_2_active' where id=p_event_id;insert into public.audit_logs(user_id,event_id,action,entity_type,entity_id,new_value) values(auth.uid(),p_event_id,'qualification_generated','round',r2.id,jsonb_build_object('method',p_method));return r2;end$$;

create or replace function public.event_leaderboard(p_event_id uuid) returns table(rank bigint,team_id uuid,team_name text,team_code citext,round_1_score integer,round_2_score integer,final_score integer) language sql stable security definer set search_path='' as $$with x as(select t.id,t.team_name,t.team_code,max(s.final_score_seconds)filter(where r.round_number=1)r1,max(s.final_score_seconds)filter(where r.round_number=2)r2 from public.teams t left join public.scores s on s.team_id=t.id left join public.rounds r on r.id=s.round_id where t.event_id=p_event_id and (public.is_event_owner(p_event_id) or t.auth_user_id=auth.uid() or exists(select 1 from public.rounds rr where rr.event_id=p_event_id and rr.result_announced)) and (r.id is null or public.is_event_owner(p_event_id) or r.result_announced) group by t.id),y as(select *,coalesce(r1,0)+case when r2 is null then 0 else r2 end final from x where r1 is not null)select row_number()over(order by final asc,r2 asc nulls last,r1 asc,id),id,team_name,team_code,r1,r2,final from y order by 1$$;

create or replace function public.publish_winners(p_event_id uuid,p_count integer) returns integer language plpgsql security definer set search_path='' as $$declare x record;begin if not public.is_event_owner(p_event_id) or p_count not in(3,4) then raise exception 'not_authorized';end if;if not exists(select 1 from public.rounds where event_id=p_event_id and round_number=2 and result_announced) then raise exception 'final_result_not_announced';end if;if exists(select 1 from public.winner_announcements where event_id=p_event_id and published) then raise exception 'winners_already_published';end if;for x in select * from public.event_leaderboard(p_event_id) where rank<=p_count loop insert into public.winner_announcements(event_id,team_id,position,published,published_at) values(p_event_id,x.team_id,x.rank,true,now());end loop;insert into public.audit_logs(user_id,event_id,action,entity_type,new_value) values(auth.uid(),p_event_id,'winners_published','winner_announcement',jsonb_build_object('count',p_count));return p_count;end$$;

create or replace function public.create_participant_team(p_event_code text,p_team_name text,p_phone text,p_auth_user_id uuid) returns public.teams language plpgsql security definer set search_path='' as $$declare e public.events;t public.teams;prefix text;seq integer;code text;begin select * into e from public.events where event_code=p_event_code::citext and status='registration_open' for update;if not found then raise exception 'event_code_not_found';end if;select count(*)+1 into seq from public.teams where event_id=e.id;prefix:=case when e.point_format='robo_race' then 'ROB' else 'DRN' end;code:=prefix||'-'||lpad(seq::text,3,'0');insert into public.teams(event_id,auth_user_id,team_name,team_code,phone_number) values(e.id,p_auth_user_id,trim(p_team_name),code,trim(p_phone)) returning * into t;insert into public.participant_credentials(team_id,code_hash)values(t.id,crypt(code,gen_salt('bf',10)));insert into public.round_teams(round_id,team_id)select id,t.id from public.rounds where event_id=e.id and round_number=1;return t;end$$;
create or replace function public.verify_participant_login(p_team_name text,p_team_code text) returns uuid language plpgsql security definer set search_path='' as $$declare cred public.participant_credentials;uid uuid;begin select c.*,t.auth_user_id into cred,uid from public.participant_credentials c join public.teams t on t.id=c.team_id where lower(t.team_name)=lower(trim(p_team_name)) and t.team_code=p_team_code::citext;if not found or (cred.locked_until is not null and cred.locked_until>now()) or cred.code_hash<>crypt(p_team_code,cred.code_hash) then if found then update public.participant_credentials set failed_attempts=failed_attempts+1,locked_until=case when failed_attempts>=4 then now()+interval '15 minutes' else locked_until end where team_id=cred.team_id;end if;return null;end if;update public.participant_credentials set failed_attempts=0,locked_until=null where team_id=cred.team_id;return uid;end$$;
revoke all on function public.create_participant_team(text,text,text,uuid) from public,anon,authenticated;grant execute on function public.create_participant_team(text,text,text,uuid) to service_role;
revoke all on function public.verify_participant_login(text,text) from public,anon,authenticated;grant execute on function public.verify_participant_login(text,text) to service_role;
grant execute on function public.is_event_owner(uuid),public.is_participant_in_event(uuid),public.is_current_team(uuid) to anon,authenticated;
