import {escapeHtml,qs} from './utils.js'
export const images={hero:'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&w=1800&q=88',robo:'https://images.unsplash.com/photo-1561144257-e32e8efc6c4f?auto=format&fit=crop&w=1000&q=85',drone:'https://images.unsplash.com/photo-1507582020474-9a35b7d455d9?auto=format&fit=crop&w=1000&q=85',event:'https://images.unsplash.com/photo-1531058020387-3be344556be6?auto=format&fit=crop&w=1000&q=85'}
export function publicNav(){return `<nav class="navbar container"><a class="brand" href="/">EVENTX<span></span></a><button class="nav-toggle" aria-label="Toggle menu">☰</button><div class="nav-links"><a href="/">Home</a><a href="/pages/winners.html">Winners</a><a href="/pages/participant-register.html">Register team</a><a class="btn btn-dark" href="/pages/coordinator-login.html">Login</a></div></nav>`}
export function coordinatorShell(content,active='dashboard'){return `<div class="app-shell"><aside class="sidebar"><a class="brand" href="/">EVENTX<span></span></a><nav class="side-nav"><a class="${active==='dashboard'?'active':''}" href="/pages/coordinator-dashboard.html">Dashboard</a><a class="${active==='events'?'active':''}" href="/pages/events.html">Events</a><a class="${active==='create'?'active':''}" href="/pages/create-event.html">Create event</a><a class="${active==='profile'?'active':''}" href="/pages/profile.html">Profile</a></nav><div class="side-bottom"><button class="btn" data-logout>Log out</button></div></aside><div><div class="mobile-topbar"><a class="brand" href="/">EVENTX<span></span></a><button class="btn" data-logout>Log out</button></div><main class="main">${content}</main></div></div>`}
export function participantShell(content){return `<div class="container"><nav class="navbar"><a class="brand" href="/">EVENTX<span></span></a><button class="btn" data-logout>Log out</button></nav><main>${content}</main></div>`}
export function skeleton(count=3){return Array.from({length:count},()=>'<div class="skeleton"></div>').join('')}
export function empty(title,copy=''){return `<div class="empty"><h3>${escapeHtml(title)}</h3><p>${escapeHtml(copy)}</p></div>`}
export function toast(message){const root=qs('#toast-root');if(!root)return;const el=document.createElement('div');el.className='toast';el.textContent=message;root.append(el);setTimeout(()=>el.remove(),3500)}
export function confirmDialog({title,message,confirmText='Continue',danger=false}){return new Promise(resolve=>{const wrap=document.createElement('div');wrap.className='dialog-backdrop';wrap.innerHTML=`<div class="dialog" role="dialog" aria-modal="true"><h2>${escapeHtml(title)}</h2><p class="muted">${escapeHtml(message)}</p><div class="button-row"><button class="btn" data-cancel>Cancel</button><button class="btn ${danger?'btn-danger':'btn-dark'}" data-confirm>${escapeHtml(confirmText)}</button></div></div>`;document.body.append(wrap);wrap.querySelector('[data-cancel]').onclick=()=>{wrap.remove();resolve(false)};wrap.querySelector('[data-confirm]').onclick=()=>{wrap.remove();resolve(true)}})}
export function wireCommon(){const toggle=qs('.nav-toggle');if(toggle)toggle.onclick=()=>qs('.nav-links')?.classList.toggle('open')}
